//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UseDict.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UseDict
    {
        public long ChatID { get; set; }
        public string Source { get; set; }
        public string Target { get; set; }
    }
}
